/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#333b4a",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#111318",
        "on-primary-fixed": "#1e3a8a",
        "primary-fixed-dim": "#bfdbfe",
        "surface-variant": "#1e293b",
        "on-primary-container": "#60a5fa",
        "primary-fixed": "#dbeafe",
        "on-secondary-container": "#cbd5e1",
        outline: "#334155",
        "on-secondary-fixed-variant": "#334155",
        background: "#101622",
        "on-error-container": "#fca5a5",
        "tertiary-fixed": "#d1fae5",
        "on-primary": "#ffffff",
        "on-surface": "#f1f5f9",
        "on-surface-variant": "#9da6b9",
        "inverse-primary": "#3b82f6",
        "secondary-container": "#1e293b",
        "on-secondary-fixed": "#0f172a",
        error: "#ef4444",
        "outline-variant": "#1e293b",
        "on-tertiary-fixed-variant": "#059669",
        surface: "#101622",
        "surface-container": "#141b29",
        "primary-container": "#1152d41a",
        "inverse-on-surface": "#0f172a",
        "inverse-surface": "#f8fafc",
        "on-tertiary-container": "#34d399",
        "on-primary-fixed-variant": "#1d4ed8",
        primary: "#1152d4",
        "tertiary-fixed-dim": "#a7f3d0",
        "surface-container-high": "#282e39",
        "surface-container-lowest": "#080c14",
        "tertiary-container": "#064e3b",
        "surface-dim": "#0c111a",
        "on-tertiary-fixed": "#064e3b",
        "on-background": "#f8fafc",
        secondary: "#64748b",
        "secondary-fixed-dim": "#e2e8f0",
        "surface-tint": "#1152d4",
        "error-container": "#7f1d1d",
        "secondary-fixed": "#f1f5f9",
        "surface-bright": "#1a2130",
        tertiary: "#10b981",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Space Grotesk", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};