
# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/traceability_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# SERVER
server.port=8080

# Blockchain
blockchain.rpc.url=http://127.0.0.1:8545
blockchain.contract.address=0x5FbDB2315678afecb367f032d93F642f64180aa3
blockchain.private.key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
blockchain.gas.price=20000000000
blockchain.gas.limit=6721975

# IPFS Kubo API
ipfs.api.url=http://127.0.0.1:5001



# AES key is loaded from environment and must not be committed.
security.aes.key-base64=${DATA_AES_KEY_BASE64}